name: CrackedLocalWhisper
options:
  bundleIdPrefix: com.crackedlocalwhisper
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: Cracked Local Whisper
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
    INFOPLIST_KEY_NSMicrophoneUsageDescription: "Cracked Local Whisper needs microphone access to transcribe your voice."

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: 0.9.0
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts.git
    from: 2.0.0

targets:
  CrackedLocalWhisper:
    type: application
    platform: macOS
    sources:
      - path: App
      - path: Views
      - path: Services
      - path: Models
      - path: Resources
    dependencies:
      - package: WhisperKit
      - package: KeyboardShortcuts
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
        SWIFT_VERSION: 5.9
    entitlements:
      path: Resources/CrackedLocalWhisper.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.device.audio-input: true
        com.apple.security.automation.apple-events: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.network.client: true
    preBuildScripts: []
    postBuildScripts: []
